<table>
    <thead>
        <tr>
            <th>name</th>	  
            <th>email</th>	 
            <th>code</th>
            <th>account_type</th>	 
            <th>contact_number</th>	 
            <th>address</th>	
            <th>policy_effective_date</th>
            <th>policy_expiry_date</th> 
            <th>contact_person_firstname</th>	 
            <th>contact_person_middlename</th>	 
            <th>contact_person_lastname</th>	 
            <th>contact_person_position</th>	 
            <th>contact_person_contact_number</th>	 
            <th>coverage_plan</th>	 
            <th>deployment</th>	 
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>