<table>
    <thead>
        <tr>
            <th>universal_id</th>	  
            <th>carewell_id</th>	 
            <th>first_name</th>	 
            <th>middle_name</th>	 
            <th>last_name</th>	 
            <th>mothers_maiden_name</th>	 
            <th>birth_date</th>	 
            <th>gender</th>	 
            <th>marital_status</th>	 
            <th>contact_number</th>	 
            <th>email</th>	 
            <th>permanent_address</th>	 
            <th>present_address</th>	 
            <th>company</th>	 
            <th>company_deployment</th>	 
            <th>payment_mode</th>	 
            <th>coverage_plan</th>	 
            <th>sss_number</th>	 
            <th>tin</th>	 
            <th>philhealth_number</th>	 
            <th>pagibig_number</th>
            <th>employee_number</th>
            <th>status</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>